# WhatATheme
markdown: kramdown

# URL of the Site
url: https://amelia.qa
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Amelia Walter-Dzikowska
# Description of the Site
description: QA & Test Automation Engineer
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Blog, QA, Testing
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: https://github.com/ameliawalter/WhatATheme/blob/master/assets/images/blue_background.jpg?raw=true
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: qamelia.quality.assurance@gmail.com
facebook_username: 
twitter_username:  
instagram_username: qa.amelia
linkedin_username: ameliawalter
github_username:  ameliawalter
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname:

# Name of the Author
author-name: Amelia Walter-Dzikowska
# URL for the Image of the Author
author-image: https://github.com/ameliawalter/WhatATheme/blob/master/assets/images/portrait.jpg?raw=true
# 60 Words About the Author
author-about: Od 2017 roku poświęcam 1/3 swojej doby i część swojego serca testom i jakości 🖤 Dotąd pracowałam w trzech ludzkich językach i w trzech językach programowania. Nieustannie szlifuję kompetencje techniczne i miękkie. Offline przemawiam na różnych konferencjach, wybierając często softskillowe tematy. Online publikuję na Instagramie i LinkedInie. Stawiam swoje pierwsze kroki jako trenerka. Cieszę się, że tu trafił*ś!    
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/ameliawalter/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
